[window]
decorations = "None"
startup_mode = "Fullscreen"
padding = { x = 0, y = 0 }
opacity = 1.0

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 12.5

[font.normal]
family = "Berkeley Mono"
style = "Condensed"

[font.bold]
family = "Berkeley Mono"
style = "Bold Condensed"

[font.italic]
family = "Berkeley Mono"
style = "Condensed Oblique"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Condensed Oblique"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"
