#!/bin/sh

# Path to the hook itself
HOOK_PATH="config/git/hooks/pre-commit"

if git diff --cached --name-only | grep -v "$HOOK_PATH" | xargs grep 'nocheckin' >/dev/null 2>&1
then
  echo "Trying to commit non-committable code."
  echo "Remove the 'nocheckin' string and try again."
  exit 1
else
  # Run local pre-commit hook if exists
  if [ -e ./.git/hooks/pre-commit ]; then
    ./.git/hooks/pre-commit "$@"
  else
    exit 0
  fi
fi
